spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/CompassEnglishBD?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=${PORT:8080}
server.address=0.0.0.0

merriam.api.key=${MERRIAM_API_KEY:7350ac6a-4af7-4eeb-8221-af2e3e09ba7b}
merriam.spanish.api.key=${MERRIAM_SPANISH_API_KEY:cf9f6e9f-e42f-491d-ab2a-6eecb77527c5}

# Anthropic API Key (OPCIONAL)
anthropic.api.key=${ANTHROPIC_KEY:}
anthropic.api.url=https://api.anthropic.com/v1/messages
anthropic.model=claude-haiku-4-5-20251001