# ================================================================
# Perfil: local-docker — BD MySQL en contenedor Docker
# Se activa automáticamente desde docker-compose.yml:
#   environment: SPRING_PROFILES_ACTIVE=local-docker
# IMPORTANTE: el host es el nombre del servicio en docker-compose,
#             no localhost
# Autor: Nassim Bouderbane Marrero
# ================================================================

# Base de datos
spring.datasource.url=jdbc:mysql://mysql:3306/CompassEnglishBD?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
